sudo: false
language: go
go:
- "1.11"
git:
  depth: 1
before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
install:
  - dep ensure
script:
  - go test -v ./...
  - mkdir build
  - env GOOS=linux GOARCH=amd64 go build -o build/agogos-host-linux
  - env GOOS=darwin GOARCH=amd64 go build -o build/agogos-host-darwin

